import type { Metadata } from "next";
import Navbar from "@/components/component/nav";
import Footer from "@/components/component/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import ClientSideStorage from "@/components/component/ClientSideStorage";
export const metadata: Metadata = {
  title: "Power Proxy",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // user info
  const user = await currentUser();
  // if (user) {
  const data = JSON.parse(JSON.stringify(user));
  // }
  const userEmail = data?.emailAddresses?.[0]?.emailAddress || "";
  return (
    <>
      <Navbar user={data} />
      {children}
      <Footer />
      <ClientSideStorage email={userEmail} />
    </>
  );
}
