import type { Metadata } from "next";
import AdminPage from "./page";

export const metadata: Metadata = {
  title: "Power Proxy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
