import type { Metadata } from "next";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import AdminSidebar from "@/components/admin/admin-sidebar";
import TestSidebar from '@/components/admin/sidebar-test'

import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { Separator } from "@radix-ui/react-separator";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Power Proxy",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";

  return (
    <>
      <SidebarProvider>
      <TestSidebar />
        <main className="w-full overflow- x-hidden ">
           
          {children}
        </main>
      </SidebarProvider>
      {/* <div className="h-screen flex flex-row justify-start"> */}
  
      {/* <div className="bg-primary flex-1 p-4 text-white">
          {children}
      </div> */}
    {/* </div> */}
    </>
  );
}
 