import type { Metadata } from "next";
import { currentUser } from "@clerk/nextjs/server";
import BillingPage from "./page";

export const metadata: Metadata = {
  title: "Power Proxy",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  const userEmail = user?.emailAddresses[0].emailAddress;
  return (
    <>
      <BillingPage userEmail={userEmail} />
    </>
  );
}
